version: "3.9"

services:
  backend:
    build: .
    container_name: python-backend-app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=backendapp
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
