version: "3.9"

services:
  backend:
    build: .
    container_name: python-backend-app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - mailhog
    env_file:
      - .env_dev
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mongo_data:
